image: maven

stages:
  - verify
  - test
  - build

verify:
  stage: verify
  script:
    - mvn -B clean verify
  tags:
    - service

test:
  stage: verify
  script:
    - mvn -B clean test
  tags:
    - service

build:
  stage: verify
  script:
    - mvn -B clean install
  artifacts:
    paths:
      - target/*.war
  tags:
    - service
